### PR TITLE
Add errorbars and enable navigation

### LINKED ISSUE #6: Add error bars on summary plot.
It would be nice to have error bars on summary plots so one could easily see whether difference could be explained by statistical fluctuations. Sadly flot lack builtin error bars but there is a plugin for it. Another possible approach is to use overlapping bar plots a la:

```
-----------
   |  |   |
-----------
```

### PR DESCRIPTION
**Pull request by Rufflewind**
- Add error bars showing the standard deviation (is there a better statistic to show?) using the errorbars plugin; fixes #6
- Allow panning and zooming using the navigate plugin (this can be useful if, say, parts of the graph are obscured by the legend)

### CODE REVIEW

**Comment by rrnewton** [comment]
This was before we came onto the project.  Does anyone else have feedback on this?

**Comment by RyanGlScott** [comment]
At the very least, this would need to be rebased to accommodate a recent change to use the `js-flot` library instead of bundling the JavaScript directly.

(Sorry for the extremely late review, @Rufflewind. Are you still interested in getting this change through?)

**Comment by Rufflewind** [comment]
I don't know how to re-attach this PR to the new branch, but here's the rebased version: https://github.com/bos/criterion/compare/master...Rufflewind:add-error-bars

**Comment by RyanGlScott** [comment]
Perhaps it would be easier to close this in favor of a new PR, then?

**Comment by Rufflewind** [comment]
Moved to #150

**Pull request closed without merging**
