### PR TITLE
Fix build with statistics 0.14

### PR DESCRIPTION
**Pull request by Shimuuar**
Support for new (not yet released) statistics 0.14. Major version bump is required because new types from statistics leak into public API.

There's also need for coordinated release of statistics and criterion. I can upload statistics but can't upload new criterion

P.S. I won't be available till Monday.

### CODE REVIEW

**Comment by rrnewton** [comment]
Hi @Shimuuar, we'd like to start getting this ready to go.  We want to do one more release on the statistics-0.13 series, maybe criterion-1.1.2.0.  It should just be bugfixes and added functionality.

Then perhaps criterion 1.2.0.0 will be the release that depends on statistics-0.14.  I'll start a branch for that now and merge this PR in there.

**Comment by rrnewton** [comment]
Ok, that's merged into [the 1.2 branch here](https://github.com/bos/criterion/commits/1.2), with [this commit](https://github.com/bos/criterion/commit/04cfcfb538356c03d19df20f24a26639c851810f).

The corresponding [travis build is here](https://travis-ci.org/bos/criterion/builds/152962936).

**Comment by rrnewton** [comment]
I think we'll do the last 1.1.X release as soon as we clean up a few loose ends.  We'll try to stay in a ready state so that when you push 0.14 out we can put out a matching criterion at the same time.

**Comment by rrnewton** [comment]
Minor: I added statistics as a submodule so that [tests will pass here](https://travis-ci.org/bos/criterion/builds/152968657).

**Comment by rrnewton** [comment]
Uh oh.  On my machine, some of the statistics properties are failing:

```
        CDF is sum of prob.: [Failed]
    *** Failed! Falsifiable (after 29 tests and 3 shrinks):
    binomial 21 0.6723083669286606
    0
    12
    CDF   = 0.22264585796494915
    Sum   = 0.22264585584591676
    Delta = 2.1190323939990208e-9
    (used seed 2015747924988581940)
```

And:
```
        Discrete CDF is OK: [Failed]
    *** Failed! Falsifiable (after 1 test):
    binomial 36 0.4293530795149135
    N=  3    p[i]=6.522069745071494e-7	p[i+1]=5.807682514515635e-6	dP=5.155475530187167e-6	relerr=1.6910907577585637e-9
    N=  5    p[i]=3.7809141675911695e-5	p[i+1]=1.9190709253235076e-4	dP=1.540979499030356e-4	relerr=4.9680469888312886e-9
    N=  7    p[i]=7.909451376875654e-4	p[i+1]=2.7225786334544038e-3	dP=1.9316334955006517e-3	relerr=9.77701098894869e-11
    N=  8    p[i]=2.7225786334544038e-3	p[i+1]=7.9909920785153e-3	dP=5.26841336570002e-3	relerr=9.931292193140317e-9
    N= 28    p[i]=0.9999777398732318	p[i+1]=0.9999955481515208	dP=1.7808278071790447e-5	relerr=2.1722151265163969e-13

    (used seed -6133568367371006187)
```

and

```
       Quantile is CDF inverse: [Failed]
    *** Failed! Falsifiable (after 28 tests):
    improperBetaDistr 4.406005379164537e-2 7.431321057890629
    Double01 0.7064506550080765
    Quantile      = 3.140238096022152e-5
    Probability   = 0.7064506550080765
    Probability'  = 0.7064506550080242
    Expected err. = 1.4836864631620987e-14
    Rel. error    = 7.402003818546542e-14
    Abs. error    = 5.229150445984487e-14
    (used seed -5833082735312527829)
```

and

```
       log density check: [Failed]
    *** Failed! Falsifiable (after 59 tests and 1026 shrinks):
    improperGammaDistr 0.9522119602111706 8.690908517635163
    2.2250738585072014e-308
    density    = 6.238976107607811e13
    logDensity = 31.764422292511565
    log p      = 31.7644222925212
    eps        = 3.033255070146662e-13
    (used seed 8922540999407031748)
```

and

```
       Quantile is CDF inverse: [Failed]
    *** Failed! Falsifiable (after 7 tests):
    studentT 1353.0867154384305
    Double01 0.799317463228931
    Quantile      = 0.8394500873866583
    Probability   = 0.799317463228931
    Probability'  = 0.7993174632289128
    Expected err. = 1.8395260820057587e-14
    Rel. error    = 2.2779006391654108e-14
    Abs. error    = 1.8207657603852567e-14
    (used seed 1394250674407640201)
```

And to get criterion tests up, need to fix an export issue:

```
    /Users/rrnewton/working_copies/criterion/tests/Tests.hs:9:41:
        Module
        ‘Statistics.Resampling.Bootstrap’
        does not export
        ‘Estimate(..)’

Test suite failure for package statistics-0.14.0.0
```

**Comment by Shimuuar** [comment]
Unfortunately these are expected failures. Writing tests for numerical code is terribly difficult because all values are approximate and formalizing notion of approximate equality is very difficult task. And if tests are written naively there's always some corner in parameter space where precision loss is just too big so test fails. I've improved some tests so they past most of the time but failing tests above are still naive (but nevertheless useful)

Oh it would be nice to add upper bounds on statistics for released versions of criterion.

**Comment by RyanGlScott** [comment]
@rrnewton: If you add me to the maintainer group for `criterion` on Hackage, I can go through and retroactively add `statistics < 0.14` bounds to all previous releases on `criterion`. (I'd still need you to do the same for `criterion` HEAD, though, since I don't have push access.)

**Comment by RyanGlScott** [comment]
I've added `statistics < 0.14` upper bounds to all previously released versions of `criterion` that need them.

**Pull request closed without merging**
