### PR TITLE
Add optparse-applicative <0.13 upper bound.

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
"Fixes" https://github.com/bos/criterion/issues/113

**Comment by RyanGlScott** [comment]
This isn't needed—the HEAD version of `criterion` builds successfully with `optparse-applicative-0.13` (and earlier).

**Comment by phadej** [comment]
I recommend adding `<0.14` bound then.

**Comment by phadej** [comment]
Feel free to close this issue if master is indeed `optparse-applicative-0.14` ready.

**Comment by RyanGlScott** [comment]
Sure, I'm always up for a PVP compliance PR. I'm also not a maintainer of this package, so I can't do anything ;)

**Pull request closed without merging**
