### PR TITLE
Ryan statistics 0.14

### PR DESCRIPTION
**Pull request by phadej**
Supersedes #139 and #137.

I'd like to change the `.travis.yml` to use https://github.com/hvr/multi-ghc-travis and test GHC's from `7.4.2` to `8.2.1`. Opinions?

If this looks ok, I'll upload `microstache` to Hackage.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Should also add: this fixes #119!

@rrnewton was the one who first created the `.travis.yml` file in its first (and current) incarnation. He greatly prefers `stack` to `cabal-install`, which explains how it looks currently. On the other hand, I personally don't care how it looks as long as it tests the versions of GHC that we care about.

**Comment by phadej** [comment]
Green. Could maintainers comment on this?

**Comment by RyanGlScott** [comment]
@phadej, can you upload `microstache` to Hackage?

**Comment by phadej** [comment]
uploaded, and removed the `.travis.yml` git-hack. Let's see what travis says.

**Pull request merged**
